### PR TITLE
build: fix up shared object version after ABI break

### LINKED ISSUE #79: ABI break requires SONAME bump
```
commit d190cabd1ad38934c741696ab0389bef008d5bda
Author: Evan Miller <emmiller@gmail.com>
Date:   Fri Aug 7 08:22:37 2020 -0400

    Bump version to 1.6.0-beta
    
    Pull request #77 introduced some ABI-breaking changes, so let's be
    polite and bump the minor version.
```
abidiff output:
```
» abidiff 153/usr/lib64/libxlsreader.so.1 160/usr/lib64/libxlsreader.so.1|o
Functions changes summary: 0 Removed, 0 Changed, 0 Added function
Variables changes summary: 0 Removed, 0 Changed, 0 Added variable
Function symbols changes summary: 1 Removed, 5 Added function symbols not referenced by debug info
Variable symbols changes summary: 0 Removed, 0 Added variable symbol not referenced by debug info

1 Removed function symbol not referenced by debug info:

  utf8_decode

5 Added function symbols not referenced by debug info:

  codepage_decode
  transcode_utf16_to_utf8
  xls_createlocale
  xls_freelocale
  xls_wcstombs_l
```
ABI breaks require a change in ELF SONAME. This was not done for libxls-1.6.0.

### PR DESCRIPTION
**Pull request by jengelh**
utf8_decode was ELF-exported and was also publicly exposed through
/usr/include/libxls/xlstool.h. It was unpulished and unexported in
commit d803ae6ba3eb4c4bce173398ba2f164fdfafdcdc. This constitutes an
ABI break. ABI-compatible changes require ELF symbol versioning or a
SONAME change, ABI breaks require a definite change in SONAME.

Fixes #79.

Since 1.6.0 is now tarnished (there is no way to tell if a libxlsreader.so.1 actually is ABI-comaptible to 1.5.3, or ABI-compatible to 1.6.0), a bump to 1.6.1 is added.

### CODE REVIEW

**Comment by evanmiller** [comment]
Thank you for letting me know.

Forgive my ignorance, but isn't this taken care of in `VERSION_INFO` which evaluates to 1 + 6 = 7? I'd rather not hard code 2:0:0

**Comment by jengelh** [comment]
1.5.3: VERSION_INFO is set to "`6:3:5`"
1.6.0: VERSION_INFO is set to "`7:0:6`"

The libtool manual states:

```
  6. If any interfaces have been removed or changed since the last
     public release, then set AGE to 0.
```

So at the very least, it should have been `7:0:0` (I was kinda low with `2`). Furthermore, "+" is a terrible idea, because it means that both "1.6.0" lead to 1+6=7 and hypothetical future version 6.1.0 lead to 6+1=7 the same value in this line:

```
VERSION_INFO=`expr $LIBXLS_MAJOR_VERSION + $LIBXLS_MINOR_VERSION`:$LIBXLS_MICRO_VERSION:$LIBXLS_MINOR_VERSION
```

**Comment by evanmiller** [comment]
Okay, I need to think about this a little bit more. I think I grabbed that `VERSION_INFO` formula from StackOverflow or something. Some of these symbols should not be exported at all.

I will add a prominent note to the current 1.6.0 and come up with a proper fix later.

**Comment by evanmiller** [comment]
For my reference: the version-info shipped in 1.6.0 was `7:0:6`

**Comment by evanmiller** [comment]
@jengelh Does this work for you? https://github.com/libxls/libxls/commit/cf5b0500e78e77a70361c6de12b08230590857dc

**Comment by jengelh** [comment]
Acceptable.

**Comment by evanmiller** [comment]
Okay, fixed in 1.6.1

**Pull request closed without merging**
