### PR TITLE
Add C++ to build as test_cpp and fix errors.

### PR DESCRIPTION
**Pull request by QuLogic**
I wasn't sure what to name it, so I went with `test_cpp` and set it to not be installed.

### CODE REVIEW

**Comment by evanmiller** [comment]
Hi, please fix the CI errors. You can also add `test_cpp` to `check_PROGRAMS`.

**Comment by QuLogic** [comment]
Where is `export CC=clang` set? I cannot find it, but it should also set `CXX=clang++`.

**Comment by evanmiller** [comment]
Should be set by `AC_PROG_CC` and `AC_PROG_CXX`

https://www.gnu.org/software/autoconf/manual/autoconf-2.66/html_node/C_002b_002b-Compiler.html

**Comment by QuLogic** [comment]
No, the `export` is done before calling `bootstrap`. I think the above change to Travis setting might do it...

**Comment by QuLogic** [comment]
I had to set it to require C++11, because the other headers seem to just be broken. This does require you to have `autoconf-archive` installed to run `./bootstrap`, or we can copy the C++11 autoconf check into the source.

However, I have no idea what's wrong with `clang` on Ubuntu. It seems to just be broken.

**Comment by jennybc** [comment]
> I had to set it to require C++11

I may not be following but this, but this might be a pretty big deal for readxl.

**Comment by QuLogic** [comment]
`readxl` doesn't use any of the C++ files, and they are not required.

**Comment by QuLogic** [comment]
OK, finally it seems to be working. I don't know why Travis' clang is broken OOTB. It works fine in a Ubuntu Trusty docker container using distro-provided packages.

**Comment by evanmiller** [comment]
Thanks for all the work on this one!

**Pull request merged**
